authuser/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name = "authuser"
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name='profile'),
]

moves/urls.py
from django.urls import path
from . import views
app_name = "moves"
urlpatterns = [
    path('exercises/', views.exercise_list, name='exercise_list'),
    path('create/', views.createExercise, name='createExercise'),
    path('exercises/<int:exercise_id>/',
         views.exercise_detail, name='exercise_detail'),
    path('add_favorite/<int:exercise_id>/',
         views.add_favorite, name='add_favorite'),
    path('add_learned/<int:exercise_id>/',
         views.add_learned, name='add_learned'),
    path('add_want_to_learn/<int:exercise_id>/',
         views.add_want_to_learn, name='add_want_to_learn'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('impressum/', views.impressum, name='impressum'),
    path('tracker/', include('tracker.urls')),
    path('moves/', include('moves.urls')),
    path('authuser/', include('authuser.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

authuser/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(blank=True, default='', unique=True)
    name = models.CharField(max_length=255, blank=True, default='')

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    favorites = models.ManyToManyField(
        'moves.Exercise', blank=True, related_name='favorited')
    learned = models.ManyToManyField(
        'moves.Exercise', blank=True, related_name='learned')
    want_to_learn = models.ManyToManyField(
        'moves.Exercise', blank=True, related_name='want_to_learn')
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name or self.email.split('@')[0]

authuser/forms.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("email",)


def signup_view(request):
    form = CustomUserCreationForm()
    return render(request, 'authuser/signup.html', {'form': form})

authuser/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import login, logout

from django.contrib.auth.decorators import login_required


def signup_view(request):
    print("YOUR METHOD", request.method)
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authuser:login')

    else:
        print("GET")
        form = CustomUserCreationForm()
    return render(request, 'authuser/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            # return redirect('articles:list')
            user = form.get_user()
            login(request, user)
            return redirect('moves:exercise_list')
    else:
        form = AuthenticationForm()
    return render(request, 'authuser/login.html', {'form': form})


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')
    return render(request, 'authuser/logout.html')


@login_required
def profile(request):
    user = request.user
    favorites = user.favorites.all()
    context = {'favorites': favorites}
    return render(request, 'authuser/profile.html', context)

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect


def index(request):

    return render(request, "home/home.html")


def impressum(request):

    return render(request, "home/impressum.html")

mysite/templates/authuser/login.html
{% extends "../base.html" %}
{% load tailwind_filters %}
{% block content %}
  <div class="flex flex-col items-center justify-center min-h-screen h-full">
    <h1 class=" text-4xl primary-text">Log in</h1>
    <form
      class="site-form w-full max-w-md mt-8 p-4"
      action="/authuser/login/"
      method="post"
    >
      {% csrf_token %}
      {{ form|crispy  }}
      <input
        type="submit"
        value="Login"
        class="mt-4 px-4 py-2 bg-[#6C63FF] text-white rounded"
      />
    </form>
    <p class="mt-4">
      Not got an account? <a href="{% url 'authuser:signup' %}" class="text-[#6C63FF]">Sign Up</a>
    </p>
  </div>
{% endblock %}

mysite/templates/authuser/logout.html
{% extends "../base.html" %}
{% block content %}


<div class="flex flex-col items-center justify-center min-h-screen">
    <h1 class=" text-4xl primary-text">Log Out</h1>
    <form class="site-form" action="/authuser/logout/" method="post">
        {% csrf_token %}
        <input  class="mt-4 px-4 py-2 bg-[#6C63FF] text-white rounded" type="submit" value="Logout" />
    </form>
  </div>



<!-- 
<a class='px-8 ml-4 py-3 solidButton' href="/authuser/login">LOGIN</a>
<a class='px-8 ml-4 py-3 solidButton' href="/authuser/signup">SIGNUP</a>
--> 

{% endblock %}

mysite/templates/authuser/profile.html
{% extends "../base.html" %}
{% load tailwind_filters %}
{% block content %}
<div class="flex flex-col items-center justify-center min-h-screen h-full">
<h1>Your Favorite Exercises</h1>
<ul>
{% for exercise in favorites %}
    <li>{{ exercise.name }}</li>
{% empty %}
    <li>No favorite exercises yet.</li>
{% endfor %}
</ul>
</div>
{% endblock %}

mysite/templates/authuser/signup.html
{% extends "../base.html" %}
{% load tailwind_filters %}
{% block content %}
<!--
<style>
    .solidButton {
        background-color: #339989;
        text-white;
        border: none;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        padding: 12px 24px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
        transition: background-color 0.3s;
    }
    .solidButton:hover {
        background-color: #7DE2D1;
    }
</style>
-->
<div class=" flex flex-col items-center justify-center min-h-screen">
    <h1 class="text-3xl font-bold mb-6  pt-[80px]">Signup</h1>
    <form class="site-form w-full max-w-md mt-8 p-4" action="/authuser/signup/" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Signup" class="mt-4 px-4 py-2 bg-[#6C63FF] text-white rounded">
    </form>
</div>
<!--
<div class="mt-6">
    <a class="px-8 ml-4 py-3 solidButton" href="/authuser/login">LOGIN</a>
    <a class="px-8 ml-4 py-3 solidButton" href="/authuser/logout">LOGOUT</a>
</div>
-->
{% endblock %}