moves/urls.py
from django.urls import path
from . import views
app_name = "moves"
urlpatterns = [
    path('exercises/', views.exercise_list, name='exercise_list'),
    path('create/', views.createExercise, name='createExercise'),
    path('exercises/<int:exercise_id>/',
         views.exercise_detail, name='exercise_detail'),
    path('add_favorite/<int:exercise_id>/',
         views.add_favorite, name='add_favorite'),
    path('add_learned/<int:exercise_id>/',
         views.add_learned, name='add_learned'),
    path('add_want_to_learn/<int:exercise_id>/',
         views.add_want_to_learn, name='add_want_to_learn'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('impressum/', views.impressum, name='impressum'),
    path('tracker/', include('tracker.urls')),
    path('moves/', include('moves.urls')),
    path('authuser/', include('authuser.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

moves/models.py
from django.db import models


# class Transition(models.Model):
#    from_position = models.ForeignKey("Exercise", related_name='from_transitions',
#                                      on_delete=models.CASCADE, limit_choices_to={'position': True})
#    to_position = models.ForeignKey('Exercise', related_name='to_transitions',
#                                    on_delete=models.CASCADE, limit_choices_to={'position': True})
#
#    def __str__(self):
#        return f'{self.from_position} -> {self.to_position}'


class Exercise(models.Model):
    DIFFICULTY_CHOICES = (
        ('easy', 'Easy'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
        ('expert', 'Expert'),
    )
    BASE_CHOICES = (
        ('lbase', 'L-Base'),
        ('standing', 'Standing'),
    )
    TYPE_CHOICES = (
        ('essential', 'Essential'),
        ('not_essential', 'Not Essential'),
    )

    name = models.CharField(max_length=255)
    difficulty = models.CharField(max_length=100, choices=DIFFICULTY_CHOICES)
    base = models.CharField(max_length=100, choices=BASE_CHOICES)
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)

    dance = models.BooleanField(default=False)
    washing_machines = models.BooleanField(default=False)
    flows = models.BooleanField(default=False)
    whips = models.BooleanField(default=False)
    pops = models.BooleanField(default=False)
    counterbalance = models.BooleanField(default=False)
    position = models.BooleanField(default=False)

    variation = models.ForeignKey('self', null=True, blank=True, related_name='variations',
                                  on_delete=models.CASCADE, limit_choices_to={'position': True})

    # entrance = models.ForeignKey(Transition, null=True, blank=True,
    #                             related_name='exercise_entrances', on_delete=models.SET_NULL)
    # exit = models.ForeignKey(Transition, null=True, blank=True,
    #                         related_name='exercise_exits', on_delete=models.SET_NULL)
    entrance_from = models.ForeignKey('self', null=True, blank=True, related_name='entrance_from_exercises',
                                      on_delete=models.SET_NULL, limit_choices_to={'position': True})
    entrance_to = models.ForeignKey('self', null=True, blank=True, related_name='entrance_to_exercises',
                                    on_delete=models.SET_NULL, limit_choices_to={'position': True})
    exit_from = models.ForeignKey('self', null=True, blank=True, related_name='exit_from_exercises',
                                  on_delete=models.SET_NULL, limit_choices_to={'position': True})
    exit_to = models.ForeignKey('self', null=True, blank=True, related_name='exit_to_exercises',
                                on_delete=models.SET_NULL, limit_choices_to={'position': True})
    transition_from = models.ForeignKey('self', null=True, blank=True, related_name='transition_from_exercises',
                                        on_delete=models.SET_NULL, limit_choices_to={'position': True})
    transition_to = models.ForeignKey('self', null=True, blank=True, related_name='transition_to_exercises',
                                      on_delete=models.SET_NULL, limit_choices_to={'position': True})

    legit = models.BooleanField(default=False)
    video_url = models.URLField()

    def __str__(self):
        return self.name


# class Transition(models.Model):
#    from_position = models.ForeignKey(
#        Exercise, related_name='from_transitions', on_delete=models.CASCADE, limit_choices_to={'position': True})
#    to_position = models.ForeignKey(Exercise, related_name='to_transitions',
#                                    on_delete=models.CASCADE, limit_choices_to={'position': True})
#
#    def __str__(self):
#        return f'{self.from_position} -> {self.to_position}'

moves/forms.py
from django import forms
from . import models
from .models import Exercise
import datetime


class CreateExercise(forms.ModelForm):

    class Meta:
        model = models.Exercise
        fields = ["name", "difficulty", "base", "type", "dance",
                  "washing_machines", "flows", "whips", "pops", "counterbalance", "position", "video_url", "variation", "entrance_from", "entrance_to", "exit_from", "exit_to", "transition_from", "transition_to"]


class FavoriteForm(forms.Form):
    exercise_id = forms.IntegerField(widget=forms.HiddenInput())

moves/views.py
from django.shortcuts import render, get_object_or_404
from .models import Exercise
from .filters import ExerciseFilter
from django.shortcuts import render, redirect
from . import forms
from .models import Exercise
import json
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import FavoriteForm
User = settings.AUTH_USER_MODEL


def exercise_list(request):
    # Instantiate the filter
    user = request.user if request.user.is_authenticated else None
    exercise_filter = ExerciseFilter(
        request.GET, queryset=Exercise.objects.all(), user=user)

    # Configure the paginator
    exercises_per_page = 10
    paginator = Paginator(exercise_filter.qs, exercises_per_page)
    page = request.GET.get('page')
    exercises_page = paginator.get_page(page)
    context = {
        'filter': exercise_filter,
        'exercises_page': exercises_page,
    }

    return render(request, 'moves/exercise_list.html', context)


def createExercise(request):
    if request.user.is_authenticated:

        if request.method == 'POST':
            # Handle each form submission separately
            if 'exercise_submit' in request.POST:
                exercise_form = forms.CreateExercise(
                    request.POST, request.FILES)
                if exercise_form.is_valid():
                    # save exercise to db
                    instance = exercise_form.save(commit=False)
                    instance.author = request.user
                    instance.save()
                    return redirect('moves:createExercise')

        else:
            exercise_form = forms.CreateExercise()
        return render(request, "moves/createExercise.html", {
            'exercise_form': exercise_form,
        })
    else:
        return render(request, "moves/createExercise.html")


def exercise_detail(request, exercise_id):
    exercise = get_object_or_404(Exercise, id=exercise_id)

    variations = Exercise.objects.filter(variation=exercise)
    entrances = Exercise.objects.filter(entrance_to=exercise)
    exits = Exercise.objects.filter(exit_from=exercise)
    transitions_from = Exercise.objects.filter(transition_from=exercise)
    transitions_to = Exercise.objects.filter(transition_to=exercise)

    context = {
        'exercise': exercise,
        'variations': variations,
        'entrances': entrances,
        'exits': exits,
        'transitions_from': transitions_from,
        'transitions_to': transitions_to,
    }

    return render(request, 'moves/exercise_detail.html', context)


@login_required
def add_favorite(request, exercise_id):
    user = request.user
    exercise = get_object_or_404(Exercise, id=exercise_id)
    user.favorites.add(exercise)
    return redirect(request.META.get('HTTP_REFERER', 'exercise_list'))


@login_required
def add_learned(request, exercise_id):
    user = request.user
    exercise = get_object_or_404(Exercise, id=exercise_id)
    user.learned.add(exercise)
    return redirect(request.META.get('HTTP_REFERER', 'exercise_list'))


@login_required
def add_want_to_learn(request, exercise_id):
    user = request.user
    exercise = get_object_or_404(Exercise, id=exercise_id)
    user.want_to_learn.add(exercise)
    return redirect(request.META.get('HTTP_REFERER', 'exercise_list'))

mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect


def index(request):

    return render(request, "home/home.html")


def impressum(request):

    return render(request, "home/impressum.html")

mysite/templates/moves/createExercise.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
{% if user.is_authenticated %}
<div class="container mx-auto mt-[120px]">
    <h2 class="text-4xl font-bold mb-8" style="color: #6C63FF;">ADD MOVE</h2>

    <div class="bg-white p-6 rounded shadow-md">
        <h3 class="text-2xl font-semibold mb-4" style="color: #071013;">Add an Acro move to the database</h3>
        <form method="POST" action="/moves/create/" enctype="multipart/form-data">
            {% csrf_token %}
            {{ exercise_form|crispy }}
            <button type="submit" name="exercise_submit" class="bg-[#6C63FF] text-white font-semibold py-2 px-4 rounded hover:bg-opacity-90">Create Move</button>
        </form>
    </div>
</div>
{% else %}
<div class="flex flex-col items-center mt-[120px] min-h-screen">
    <h2 class="text-2xl font-semibold mb-4 text-gray-800">Get Started</h2>
    <a href="/authuser/signup" class="mb-4 px-6 py-3 bg-[#6C63FF] text-white rounded font-semibold">Sign Up</a>
    <a href="/authuser/login" class="px-6 py-3 bg-gray-300 text-gray-800 rounded font-semibold">Log In</a>

</div>
{% endif %}
{% endblock %}

mysite/templates/moves/exercise_detail.html
{% extends "base.html" %}
{% load youtube_filters %}
{% block content %}
<style>
    iframe {
        top:0;
        left:0;
        width:70%;
        height:100%;
    }
</style>
<div class="container mx-auto mt-[120px] min-h-screen ">
    <div class="text-center ">
        <h2 class="text-4xl font-bold mb-8" style="color: #6C63FF;">{{ exercise.name }}</h2>
        <p>Difficulty: {{ exercise.difficulty }}</p>
        <p>Base: {{ exercise.base }}</p>
        <p>Type: {{ exercise.type }}</p>
        <!-- Add other exercise fields you want to display here -->

        {% if exercise.video_url %}
            <div class="video-container h_iframe mb-8 flex items-center justify-center">
                <iframe src="https://www.youtube.com/embed/{{ exercise.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        {% endif %}
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div>
            <h2 class="text-2xl font-bold mb-4" style="color: #6C63FF;">Variations</h2>
            <ul>
                {% for variation in variations %}
                    <li class="mb-4">
                        <h3 class="text-xl font-bold mb-2" style="color: #6C63FF;">{{ variation.name }}</h3>
                        <p>Difficulty: {{ variation.difficulty }}</p>
                        {% if variation.video_url %}
                            <div class="video-container h_iframe">
                                <iframe src="https://www.youtube.com/embed/{{ variation.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li>No variations found.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div>
            <h2 class="text-2xl font-bold mb-4" style="color: #6C63FF;">Entrances</h2>
            <ul>
                {% for variation in entrances %}
                    <li class="mb-4">
                        <h3 class="text-xl font-bold mb-2" style="color: #6C63FF;">{{ variation.name }}</h3>
                        <p>Difficulty: {{ variation.difficulty }}</p>
                        {% if variation.video_url %}
                            <div class="video-container h_iframe">
                                <iframe src="https://www.youtube.com/embed/{{ variation.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li>No entrances found.</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h2 class="text-2xl font-bold mb-4" style="color: #6C63FF;">Exits</h2>
            <ul>
                {% for variation in exits %}
                    <li class="mb-4">
                        <h3 class="text-xl font-bold mb-2" style="color: #6C63FF;">{{ variation.name }}</h3>
                        <p>Difficulty: {{ variation.difficulty }}</p>
                        {% if variation.video_url %}
                            <div class="video-container h_iframe">
                                <iframe src="https://www.youtube.com/embed/{{ variation.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li>No exits found.</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h2 class="text-2xl font-bold mb-4" style="color: #6C63FF;">Transition From {{exercise.name}}</h2>
            <ul>
                {% for variation in transition_from %}
                    <li class="mb-4">
                        <h3 class="text-xl font-bold mb-2" style="color: #6C63FF;">{{ variation.name }}</h3>
                        <p>Difficulty: {{ variation.difficulty }}</p>
                        {% if variation.video_url %}
                            <div class="video-container h_iframe">
                                <iframe src="https://www.youtube.com/embed/{{ variation.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li>No transition found starting from {{ exercise.name }}.</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h2 class="text-2xl font-bold mb-4" style="color: #6C63FF;">Transitions To {{exercise.name}}</h2>
            <ul>
                {% for variation in transition_to %}
                    <li class="mb-4">
                        <h3 class="text-xl font-bold mb-2" style="color: #6C63FF;">{{ variation.name }}</h3>
                        <p>Difficulty: {{ variation.difficulty }}</p>
                        {% if variation.video_url %}
                            <div class="video-container h_iframe">
                                <iframe src="https://www.youtube.com/embed/{{ variation.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li>No variations found going into {{ exercise.name }}.</li>
                {% endfor %}
            </ul>
        </div>

        <!-- Entrances, Exits, Transitions starting, and Transitions coming sections go here -->
    </div>
    
    
</div>
{% endblock %}

mysite/templates/moves/exercise_list.html
{% extends "base.html" %}

{% load youtube_filters %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}

<style>
    iframe {
        top:0;
        left:0;
        width:100%;
        height:100%;
    }
</style>
<div class=" min-h-screen">
<div class="container mx-auto mt-[120px]">
    <h2 class="text-4xl font-bold mb-8" style="color: #6C63FF;">MOVES</h2>
    <form action="" method="get" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 ">
        <div class="mb-4 form-cont">
            <div >
                {{ filter.form.difficulty|as_crispy_field }}
                {{ filter.form.type|as_crispy_field }}
                {{ filter.form.base|as_crispy_field }}
            </div>
            <button id="more-settings-button" type="button" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
                    More Filters
            </button>
            <div id="more-settings" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 hidden mt-4">
                {{ filter.form.dance|as_crispy_field }}
                {{ filter.form.flows|as_crispy_field }}
                {{ filter.form.washing_machines|as_crispy_field }}
                {{ filter.form.whips|as_crispy_field }}
                {{ filter.form.pops|as_crispy_field }}
                {{ filter.form.counterbalance|as_crispy_field }}
                {{ filter.form.position|as_crispy_field }}
            </div>
            <button id="advanced-settings-button" type="button" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
                Advanced Filters
            </button>
            <div id="advanced-settings" class="hidden mt-4">
                {{ filter.form.favorite|as_crispy_field }}
                {{ filter.form.learned|as_crispy_field }}
                {{ filter.form.want_to_learn|as_crispy_field }}
                {{ filter.form.variation|as_crispy_field }}
                {{ filter.form.entrance_to|as_crispy_field }}
                {{ filter.form.exit_from|as_crispy_field }}
                {{ filter.form.transition_from|as_crispy_field }}
                {{ filter.form.transition_to|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="bg-[#6C63FF] hover:bg-blue-800 text-white font-bold py-2 px-4 rounded">
            Filter
        </button>
    </form>
</div>
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    {% for exercise in exercises_page %}
        <div class="bg-white shadow-md rounded p-6">
            
            <a class="text-xl font-semibold mb-4" href="{% url 'moves:exercise_detail' exercise.id %}">{{ exercise.name }}</a>
            <p class="mb-4">{{ exercise.difficulty }}</p>
            {% if exercise.video_url %}
                <div class="video-container h_iframe">
                    <iframe src="https://www.youtube.com/embed/{{ exercise.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            {% endif %}
            <div class="flex ">
            <div class="m-2">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'moves:add_favorite' exercise.id %}">
                    {% csrf_token %}
                    <button type="submit" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                        Add to Favorites
                    </button>
                </form>
                {% else %}
                    <button href="/authuser/signup" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                        Add to Favorites
                    </button>
                {% endif %}
            </div>
            <div class="m-2">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'moves:add_learned' exercise.id %}">
                    {% csrf_token %}
                    <button type="submit" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                        Already Learned
                    </button>
                </form>
                {% else %}
                    <button href="/authuser/signup" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                        Already Learned
                    </button>
                {% endif %}
            </div>

            
            <div class="m-2">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'moves:add_want_to_learn' exercise.id %}">
                        {% csrf_token %}
                        <button type="submit" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                            Want To Learn
                        </button>
                    </form>
                {% else %}
                    <button href="/authuser/signup" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mt-4">
                        Want To Learn
                    </button>
                {% endif %}
            </div>
        </div>
        </div>
    {% endfor %}
</div>
{% if exercises_page.has_next %}
    <div class="mt-6 text-center">
        <a href="?page={{ exercises_page.next_page_number }}{% if request.GET.urlencode|slice:'5:' %}&{{ request.GET.urlencode|slice:'5:' }}{% endif %}" class="bg-[#6C63FF] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Load More
        </a>
    </div>
{% endif %}
</div>
    <script>
        document.getElementById("advanced-settings-button").addEventListener("click", function() {
            var advancedSettings = document.getElementById("advanced-settings");
            advancedSettings.classList.toggle("hidden");
        });
        document.getElementById("more-settings-button").addEventListener("click", function() {
            var advancedSettings = document.getElementById("more-settings");
            advancedSettings.classList.toggle("hidden");
        });
    </script>

    <!-- Rest of the template -->

{% endblock %}

mysite/templates/moves/exercise_list2.html
{% extends "base.html" %}

{% load youtube_filters %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
<style>
   
    iframe {
    top:0;
    left:0;
    width:100%;
    height:100%;
    }
    

</style>

<div class="container mx-auto mt-[120px] ">
    <h2 class="text-4xl font-bold mb-8" style="color: #6C63FF;">MOVES</h2>
    <form action="" method="get" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 ">
        <div class="mb-4 form-cont">
            {{ filter.form|crispy }}
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Filter
        </button>
    </form>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for exercise in filter.qs %}
            <div class="bg-white shadow-md rounded p-6">
                
                <a class="text-xl font-semibold mb-4" href="{% url 'moves:exercise_detail' exercise.id %}">{{ exercise.name }}</a>
                <p class="mb-4">{{ exercise.difficulty }}</p>
                {% if exercise.video_url %}
                    <div class="video-container h_iframe">
                        <iframe src="https://www.youtube.com/embed/{{ exercise.video_url|get_youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}